# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 测试

on:
  push:
    branches:
      - test

jobs:
  build-and-publish-npm:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.11.0"

      - name: 使用 Node.js ${{ matrix.node-version }} 版本
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Update npm
        run: npm install -g npm@latest

      - name: 安装依赖
        run: pnpm install

      - name: 构建测试
        run: |
          pnpm run build
